export const ESTADOS = [
  { uf: 'PB', nome: 'Paraíba', n: 223, baixo: 75, medio: 90, alto: 42, critico: 5, nd: 11, ativo: true },
  { uf: 'RN', nome: 'Rio Gde. Norte', n: 167, baixo: 61, medio: 59, alto: 29, critico: 12, nd: 6, ativo: true },
  { uf: 'CE', nome: 'Ceará', n: 184, ativo: true },
  { uf: 'PE', nome: 'Pernambuco', n: 185, ativo: true },
  { uf: 'MA', nome: 'Maranhão', n: 217, ativo: true },
  { uf: 'PI', nome: 'Piauí', n: 224, ativo: true },
  { uf: 'AL', nome: 'Alagoas', n: 102, ativo: true },
  { uf: 'SE', nome: 'Sergipe', n: 75, ativo: true },
  { uf: 'BA', nome: 'Bahia', n: 417, ativo: true },
  { uf: 'MG', nome: 'Minas Gerais', n: 853, ativo: false },
  { uf: 'SP', nome: 'São Paulo', n: 645, ativo: false },
  { uf: 'RJ', nome: 'Rio de Janeiro', n: 92, ativo: false },
  { uf: 'ES', nome: 'Espírito Santo', n: 78, ativo: false },
  { uf: 'PR', nome: 'Paraná', n: 399, ativo: false },
  { uf: 'SC', nome: 'Santa Catarina', n: 295, ativo: false },
  { uf: 'RS', nome: 'Rio Gde. Sul', n: 497, ativo: false },
  { uf: 'MS', nome: 'Mato Grosso do Sul', n: 79, ativo: false },
  { uf: 'MT', nome: 'Mato Grosso', n: 141, ativo: false },
  { uf: 'GO', nome: 'Goiás', n: 246, ativo: false },
  { uf: 'DF', nome: 'Dist. Federal', n: 1, ativo: false },
  { uf: 'AM', nome: 'Amazonas', n: 62, ativo: false },
  { uf: 'PA', nome: 'Pará', n: 144, ativo: false },
  { uf: 'AC', nome: 'Acre', n: 22, ativo: false },
  { uf: 'RO', nome: 'Rondônia', n: 52, ativo: false },
  { uf: 'RR', nome: 'Roraima', n: 15, ativo: false },
  { uf: 'AP', nome: 'Amapá', n: 16, ativo: false },
  { uf: 'TO', nome: 'Tocantins', n: 139, ativo: false },
]

export const RELS = {
  PB: {
    uf: 'PB',
    nome: 'Paraíba',
    n: 223,
    baixo: 75,
    medio: 90,
    alto: 42,
    critico: 5,
    nd: 11,
    data: '26/03/2026',
    ref: '2020–2025',
    score_medio: 68.9,
    score_med: 68.5,
    eorcam: 95.6,
    lliq: 0.083,
    aut: 0.028,
    achados: [
      {
        t: 'pos',
        titulo: 'Movimento CAUC em março',
        body: '76 municípios tiveram pendências alteradas — 20 migraram de Médio para Risco Baixo após quitações federais.',
      },
      {
        t: 'pos',
        titulo: 'João Pessoa no topo',
        body: 'Score 100,0. Execução orçamentária de 91,1%, zero RP processados, CAUC regular.',
      },
      {
        t: 'neg',
        titulo: '5 municípios críticos',
        body: 'Lucena, Jericó, Bom Jesus, Damião e São José de Caiana mantêm CAUC grave e execução abaixo de 70%.',
      },
      {
        t: 'neg',
        titulo: 'Autonomia crítica em 95%',
        body: '213 municípios com receita tributária própria abaixo de 8% da RCL — dependência estrutural do FPM.',
      },
    ],
  },
  RN: {
    uf: 'RN',
    nome: 'Rio Grande do Norte',
    n: 167,
    baixo: 61,
    medio: 59,
    alto: 29,
    critico: 12,
    nd: 6,
    data: '31/03/2026',
    ref: '2020–2025',
    score_medio: 65.2,
    score_med: 64.8,
    eorcam: 91.2,
    lliq: 0.071,
    aut: 0.031,
    achados: [
      {
        t: 'pos',
        titulo: 'Maior % de Risco Baixo do NE',
        body: '37% dos municípios classificados como Risco Baixo — maior proporção entre os estados nordestinos já processados.',
      },
      {
        t: 'neg',
        titulo: '12 municípios críticos',
        body: 'Maior concentração proporcional de críticos. Seis municípios com execução abaixo de 65%.',
      },
      {
        t: 'neg',
        titulo: 'Natal: alerta de dispensa',
        body: 'Capital com alta concentração de contratações por dispensa de licitação (>30%).',
      },
      {
        t: 'pos',
        titulo: 'Transparência sólida',
        body: 'Entrega de RREO consistente em mais de 85% dos municípios nos 6 anos analisados.',
      },
    ],
  },
}
