export const UF_METADATA = [
  { uf: 'PB', nome: 'Paraíba', municipios: 223, geojsonPath: '/pb_geo.geojson' },
  { uf: 'RN', nome: 'Rio Grande do Norte', municipios: 167 },
  { uf: 'CE', nome: 'Ceará', municipios: 184, geojsonPath: '/ce_geo.geojson' },
  { uf: 'PE', nome: 'Pernambuco', municipios: 185, geojsonPath: '/pe_geo.geojson' },
  { uf: 'MA', nome: 'Maranhão', municipios: 217, geojsonPath: '/ma_geo.geojson' },
  { uf: 'PI', nome: 'Piauí', municipios: 224, geojsonPath: '/pi_geo.geojson' },
  { uf: 'AL', nome: 'Alagoas', municipios: 102, geojsonPath: '/al_geo.geojson' },
  { uf: 'SE', nome: 'Sergipe', municipios: 75, geojsonPath: '/se_geo.geojson' },
  { uf: 'BA', nome: 'Bahia', municipios: 417, geojsonPath: '/ba_geo.geojson' },
  { uf: 'MG', nome: 'Minas Gerais', municipios: 853 },
  { uf: 'SP', nome: 'São Paulo', municipios: 645 },
  { uf: 'RJ', nome: 'Rio de Janeiro', municipios: 92 },
  { uf: 'ES', nome: 'Espírito Santo', municipios: 78 },
  { uf: 'PR', nome: 'Paraná', municipios: 399 },
  { uf: 'SC', nome: 'Santa Catarina', municipios: 295 },
  { uf: 'RS', nome: 'Rio Grande do Sul', municipios: 497 },
  { uf: 'MS', nome: 'Mato Grosso do Sul', municipios: 79 },
  { uf: 'MT', nome: 'Mato Grosso', municipios: 141 },
  { uf: 'GO', nome: 'Goiás', municipios: 246 },
  { uf: 'DF', nome: 'Distrito Federal', municipios: 1 },
  { uf: 'AM', nome: 'Amazonas', municipios: 62 },
  { uf: 'PA', nome: 'Pará', municipios: 144 },
  { uf: 'AC', nome: 'Acre', municipios: 22 },
  { uf: 'RO', nome: 'Rondônia', municipios: 52 },
  { uf: 'RR', nome: 'Roraima', municipios: 15 },
  { uf: 'AP', nome: 'Amapá', municipios: 16 },
  { uf: 'TO', nome: 'Tocantins', municipios: 139 },
]

export const UF_METADATA_BY_UF = Object.fromEntries(UF_METADATA.map((item) => [item.uf, item]))
