"""
Build frontend map data for the landing-page Brazil coverage map.

The source is a GeoJSON with one feature per UF. We project it to a Brazil-
specific CRS, simplify the geometry for a lighter landing-page asset and emit
an ES module consumed by the frontend component.
"""

from __future__ import annotations

from pathlib import Path

import geopandas as gpd
from shapely.geometry import MultiPolygon, Polygon


ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE = ROOT / "data" / "raw" / "geo" / "BR" / "br_states_source.geojson"
OUTPUT = ROOT / "frontend" / "lib" / "brazilMapData.js"

TARGET_CRS = "EPSG:5880"
SIMPLIFY_TOLERANCE = 10000
TARGET_WIDTH = 560
PADDING = 14


def format_num(value: float) -> str:
    text = f"{value:.1f}"
    if text.endswith(".0"):
        return text[:-2]
    return text


def ring_to_path(ring: list[tuple[float, float]]) -> str:
    if not ring:
        return ""

    points = [f"M {format_num(ring[0][0])},{format_num(ring[0][1])}"]
    points.extend(f"L {format_num(x)},{format_num(y)}" for x, y in ring[1:])
    points.append("Z")
    return " ".join(points)


def polygon_to_path(polygon: Polygon) -> str:
    parts = [ring_to_path(list(polygon.exterior.coords))]
    parts.extend(ring_to_path(list(interior.coords)) for interior in polygon.interiors)
    return " ".join(part for part in parts if part)


def geometry_to_path(geometry: Polygon | MultiPolygon) -> str:
    if isinstance(geometry, Polygon):
        return polygon_to_path(geometry)
    if isinstance(geometry, MultiPolygon):
        return " ".join(polygon_to_path(polygon) for polygon in geometry.geoms)
    raise TypeError(f"Unsupported geometry type: {geometry.geom_type}")


def normalize_geometry(gdf: gpd.GeoDataFrame) -> tuple[gpd.GeoDataFrame, int]:
    minx, miny, maxx, maxy = gdf.total_bounds
    width = maxx - minx
    height = maxy - miny
    scale = (TARGET_WIDTH - PADDING * 2) / width
    target_height = int(round(height * scale + PADDING * 2))

    def transform_coords(coords: list[tuple[float, float]]) -> list[tuple[float, float]]:
        return [
            ((x - minx) * scale + PADDING, (maxy - y) * scale + PADDING)
            for x, y in coords
        ]

    def transform_geometry(geometry: Polygon | MultiPolygon):
        if isinstance(geometry, Polygon):
            exterior = transform_coords(list(geometry.exterior.coords))
            interiors = [transform_coords(list(ring.coords)) for ring in geometry.interiors]
            return Polygon(exterior, interiors)
        if isinstance(geometry, MultiPolygon):
            return MultiPolygon([transform_geometry(polygon) for polygon in geometry.geoms])
        raise TypeError(f"Unsupported geometry type: {geometry.geom_type}")

    normalized = gdf.copy()
    normalized["geometry"] = normalized["geometry"].map(transform_geometry)
    return normalized, target_height


def build_module() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(
            f"Brazil states source file not found: {SOURCE}\n"
            "Download a source GeoJSON before running this generator."
        )

    gdf = gpd.read_file(SOURCE)
    if "id" not in gdf.columns or "Estado" not in gdf.columns:
        raise ValueError("Source must include 'id' and 'Estado' columns.")

    gdf = gdf[["id", "Estado", "geometry"]].copy()
    gdf = gdf.rename(columns={"id": "uf", "Estado": "name"})
    gdf["uf"] = gdf["uf"].astype(str).str.upper()
    gdf = gdf.sort_values("uf").reset_index(drop=True)
    gdf = gdf.to_crs(TARGET_CRS)
    gdf["geometry"] = gdf["geometry"].simplify(SIMPLIFY_TOLERANCE, preserve_topology=True)
    gdf, target_height = normalize_geometry(gdf)

    entries: list[str] = []
    for row in gdf.itertuples(index=False):
        path = geometry_to_path(row.geometry)
        entries.append(
            "  {\n"
            f"    uf: '{row.uf}',\n"
            f"    name: '{row.name}',\n"
            f"    d: `{path}`,\n"
            "  }"
        )

    module = (
        "// Generated by src/utils/build_brazil_map_data.py\n"
        f"// Source: {SOURCE.as_posix()}\n"
        f"// Projection: {TARGET_CRS}\n"
        "\n"
        f"export const BRAZIL_MAP_VIEWBOX = '0 0 {TARGET_WIDTH} {target_height}'\n"
        "\n"
        "export const BRAZIL_MAP_STATES = [\n"
        + ",\n".join(entries)
        + "\n]\n"
    )

    OUTPUT.write_text(module, encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    build_module()
